describe('Turing Cafe landing page', () => {

  it('should display correct information on page load', () => {
    cy.visit('http://localhost:3000/')
      .contains('Turing Cafe Reservations')
      .get('form')
      .find('input')
      .should('have.length', 4)

    cy.get('input')
      .eq(0)
      .get('input')
      .should('have.attr', 'value', '')
      .eq(1)
      .get('input')
      .should('have.attr', 'value', '')
      .get('input')
      .eq(2)
      .should('have.attr', 'value', '')
      .get('input')
      .eq(3)
      .should('have.attr', 'value', '')

    cy.get('button:first')
      .should('have.text', 'Make Reservation')

    cy.get('.card')
      .should('have.length', 9)

    cy.get('.card:first')
      .find('h2')
      .should('have.text', 'Christie')
      .get('.card:first > p')
      .eq(0)
      .should('have.text', '12/29')
      .get('.card:first > p')
      .eq(1)
      .should('have.text', '7:00')
      .get('.card:first > p')
      .eq(2)
      .should('have.text', 'Number of guests: 12')
      .get('.card:first > button')
      .should('have.text', 'Cancel')
  })

  it('should update form input when data is entered', () => {
    cy.visit('http://localhost:3000/')
      .get('input:first')
      .should('have.attr', 'value', '')
      .type('Ali')
      .should('have.attr', 'value', 'Ali')
  })

  it('should add a card when a new reservation is entered', () => {
    cy.visit('http://localhost:3000/')
      .get('input')
      .eq(0)
      .type('Ali')
      .get('input')
      .eq(1)
      .type('2/20')
      .get('input')
      .eq(2)
      .type('5:00')
      .get('input')
      .eq(3)
      .type('2')
      .get('button:first')
      .click()

    cy.get('.card')
      .should('have.length', 10)
      .eq(9)
      .contains('Ali')
      .get('.card')
      .eq(9)
      .contains('2/20')
      .get('.card')
      .eq(9)
      .contains('5:00')
      .get('.card')
      .eq(9)
      .contains('Number of guests: 2')
  })
})
